version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bms_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: bms_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=bms_db
      - SECRET_KEY=bms_super_secret_key_2026
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo_data:
